version: '2'

services:
    db:
        image: mysql
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=wordpress
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress

    wp:
        depends_on:
            - db
        image: wordpress
        restart: always
        links:
            - db:mysql
        ports:
            - "1337:80"
        environment:
            - WORDPRESS_DB_PASSWORD=wordpress
